# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dem_builder_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DEMBuilderDialogBase(object):
    def setupUi(self, DEMBuilderDialogBase):
        DEMBuilderDialogBase.setObjectName("DEMBuilderDialogBase")
        DEMBuilderDialogBase.resize(724, 680)
        self.button_box = QtWidgets.QDialogButtonBox(DEMBuilderDialogBase)
        self.button_box.setGeometry(QtCore.QRect(340, 620, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.layoutWidget = QtWidgets.QWidget(DEMBuilderDialogBase)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 40, 421, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectOceanAge = QgsMapLayerComboBox(self.layoutWidget)
        self.selectOceanAge.setObjectName("selectOceanAge")
        self.horizontalLayout.addWidget(self.selectOceanAge)
        self.selectBathyButton = QtWidgets.QToolButton(self.layoutWidget)
        self.selectBathyButton.setObjectName("selectBathyButton")
        self.horizontalLayout.addWidget(self.selectBathyButton)
        self.layoutWidget1 = QtWidgets.QWidget(DEMBuilderDialogBase)
        self.layoutWidget1.setGeometry(QtCore.QRect(170, 110, 421, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectPaleoBathy = QgsMapLayerComboBox(self.layoutWidget1)
        self.selectPaleoBathy.setObjectName("selectPaleoBathy")
        self.horizontalLayout_2.addWidget(self.selectPaleoBathy)
        self.selectPBathyButton = QtWidgets.QToolButton(self.layoutWidget1)
        self.selectPBathyButton.setObjectName("selectPBathyButton")
        self.horizontalLayout_2.addWidget(self.selectPBathyButton)
        self.layoutWidget2 = QtWidgets.QWidget(DEMBuilderDialogBase)
        self.layoutWidget2.setGeometry(QtCore.QRect(170, 220, 421, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selectSbathy = QgsMapLayerComboBox(self.layoutWidget2)
        self.selectSbathy.setAllowEmptyLayer(True)
        self.selectSbathy.setShowCrs(True)
        self.selectSbathy.setExcludedProviders(['"ogr"'])
        self.selectSbathy.setObjectName("selectSbathy")
        self.horizontalLayout_3.addWidget(self.selectSbathy)
        self.selectTopoButton = QtWidgets.QToolButton(self.layoutWidget2)
        self.selectTopoButton.setObjectName("selectTopoButton")
        self.horizontalLayout_3.addWidget(self.selectTopoButton)
        self.layoutWidget3 = QtWidgets.QWidget(DEMBuilderDialogBase)
        self.layoutWidget3.setGeometry(QtCore.QRect(170, 300, 421, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectMask = QgsMapLayerComboBox(self.layoutWidget3)
        self.selectMask.setAllowEmptyLayer(True)
        self.selectMask.setShowCrs(True)
        self.selectMask.setExcludedProviders(['"gdal"'])
        self.selectMask.setObjectName("selectMask")
        self.horizontalLayout_4.addWidget(self.selectMask)
        self.addMaskButton = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.addMaskButton.sizePolicy().hasHeightForWidth())
        self.addMaskButton.setSizePolicy(sizePolicy)
        self.addMaskButton.setMaximumSize(QtCore.QSize(65, 25))
        self.addMaskButton.setObjectName("addMaskButton")
        self.horizontalLayout_4.addWidget(self.addMaskButton)
        self.label = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 40, 141, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 121, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 131, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_4.setGeometry(QtCore.QRect(30, 300, 91, 17))
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(DEMBuilderDialogBase)
        self.listWidget.setGeometry(QtCore.QRect(170, 330, 351, 101))
        self.listWidget.setObjectName("listWidget")
        self.textEdit = QtWidgets.QTextEdit(DEMBuilderDialogBase)
        self.textEdit.setGeometry(QtCore.QRect(10, 600, 461, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_5.setGeometry(QtCore.QRect(16, 170, 111, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_6.setGeometry(QtCore.QRect(20, 580, 47, 13))
        self.label_6.setObjectName("label_6")
        self.ageBox = QgsSpinBox(DEMBuilderDialogBase)
        self.ageBox.setGeometry(QtCore.QRect(170, 160, 90, 27))
        self.ageBox.setObjectName("ageBox")
        self.outputFile = QgsFileWidget(DEMBuilderDialogBase)
        self.outputFile.setGeometry(QtCore.QRect(160, 470, 419, 21))
        self.outputFile.setObjectName("outputFile")
        self.label_7 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_7.setGeometry(QtCore.QRect(30, 470, 61, 16))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(DEMBuilderDialogBase)
        self.button_box.accepted.connect(DEMBuilderDialogBase.accept)
        self.button_box.rejected.connect(DEMBuilderDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(DEMBuilderDialogBase)

    def retranslateUi(self, DEMBuilderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DEMBuilderDialogBase.setWindowTitle(_translate("DEMBuilderDialogBase", "Paleogeography"))
        self.selectBathyButton.setText(_translate("DEMBuilderDialogBase", "..."))
        self.selectPBathyButton.setText(_translate("DEMBuilderDialogBase", "..."))
        self.selectTopoButton.setText(_translate("DEMBuilderDialogBase", "..."))
        self.addMaskButton.setText(_translate("DEMBuilderDialogBase", "Add"))
        self.label.setText(_translate("DEMBuilderDialogBase", "Ocean age"))
        self.label_2.setText(_translate("DEMBuilderDialogBase", "Paleoocean bathimetry"))
        self.label_3.setText(_translate("DEMBuilderDialogBase", "Shallow sea bathymetry"))
        self.label_4.setText(_translate("DEMBuilderDialogBase", "Mask layers"))
        self.label_5.setText(_translate("DEMBuilderDialogBase", "Age of reconstruction"))
        self.label_6.setText(_translate("DEMBuilderDialogBase", "Info:"))
        self.label_7.setText(_translate("DEMBuilderDialogBase", "Output file"))

from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
from qgsspinbox import QgsSpinBox
