# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mask_maker_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_MaskMakerDialogBase(object):
    def setupUi(self, MaskMakerDialogBase):
        MaskMakerDialogBase.setObjectName("MaskMakerDialogBase")
        MaskMakerDialogBase.resize(880, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MaskMakerDialogBase.sizePolicy().hasHeightForWidth())
        MaskMakerDialogBase.setSizePolicy(sizePolicy)
        MaskMakerDialogBase.setSizeGripEnabled(True)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(MaskMakerDialogBase)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Tabs = QtWidgets.QTabWidget(MaskMakerDialogBase)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 491, 472))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectSsMask = QgsMapLayerComboBox(self.groupBox)
        self.selectSsMask.setAllowEmptyLayer(True)
        self.selectSsMask.setShowCrs(True)
        self.selectSsMask.setExcludedProviders(['"gdal"'])
        self.selectSsMask.setObjectName("selectSsMask")
        self.horizontalLayout_4.addWidget(self.selectSsMask)
        self.selectSsButton = QtWidgets.QToolButton(self.groupBox)
        self.selectSsButton.setObjectName("selectSsButton")
        self.horizontalLayout_4.addWidget(self.selectSsButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectSsMaskLine = QgsMapLayerComboBox(self.groupBox)
        self.selectSsMaskLine.setAllowEmptyLayer(True)
        self.selectSsMaskLine.setShowCrs(True)
        self.selectSsMaskLine.setExcludedProviders(['"gdal"'])
        self.selectSsMaskLine.setObjectName("selectSsMaskLine")
        self.horizontalLayout_6.addWidget(self.selectSsMaskLine)
        self.selectSsLineButton = QtWidgets.QToolButton(self.groupBox)
        self.selectSsLineButton.setObjectName("selectSsLineButton")
        self.horizontalLayout_6.addWidget(self.selectSsLineButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputPath = QgsFileWidget(self.groupBox_4)
        self.outputPath.setObjectName("outputPath")
        self.verticalLayout.addWidget(self.outputPath)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.selectCoastlineMask = QgsMapLayerComboBox(self.groupBox_2)
        self.selectCoastlineMask.setAllowEmptyLayer(True)
        self.selectCoastlineMask.setShowCrs(True)
        self.selectCoastlineMask.setExcludedProviders(['"gdal"'])
        self.selectCoastlineMask.setObjectName("selectCoastlineMask")
        self.horizontalLayout_8.addWidget(self.selectCoastlineMask)
        self.selectCoastButton = QtWidgets.QToolButton(self.groupBox_2)
        self.selectCoastButton.setObjectName("selectCoastButton")
        self.horizontalLayout_8.addWidget(self.selectCoastButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.selectCoastlineMaskLine = QgsMapLayerComboBox(self.groupBox_2)
        self.selectCoastlineMaskLine.setAllowEmptyLayer(True)
        self.selectCoastlineMaskLine.setShowCrs(True)
        self.selectCoastlineMaskLine.setExcludedProviders(['"gdal"'])
        self.selectCoastlineMaskLine.setObjectName("selectCoastlineMaskLine")
        self.horizontalLayout_9.addWidget(self.selectCoastlineMaskLine)
        self.selectCoastLineButton = QtWidgets.QToolButton(self.groupBox_2)
        self.selectCoastLineButton.setObjectName("selectCoastLineButton")
        self.horizontalLayout_9.addWidget(self.selectCoastLineButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.selectCshMask = QgsMapLayerComboBox(self.groupBox_3)
        self.selectCshMask.setAllowEmptyLayer(True)
        self.selectCshMask.setShowCrs(True)
        self.selectCshMask.setExcludedProviders(['"gdal"'])
        self.selectCshMask.setObjectName("selectCshMask")
        self.horizontalLayout_5.addWidget(self.selectCshMask)
        self.selectCsButton = QtWidgets.QToolButton(self.groupBox_3)
        self.selectCsButton.setObjectName("selectCsButton")
        self.horizontalLayout_5.addWidget(self.selectCsButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.selectCshMaskLine = QgsMapLayerComboBox(self.groupBox_3)
        self.selectCshMaskLine.setAllowEmptyLayer(True)
        self.selectCshMaskLine.setShowCrs(True)
        self.selectCshMaskLine.setExcludedProviders(['"gdal"'])
        self.selectCshMaskLine.setObjectName("selectCshMaskLine")
        self.horizontalLayout_7.addWidget(self.selectCshMaskLine)
        self.selectCsLineButton = QtWidgets.QToolButton(self.groupBox_3)
        self.selectCsLineButton.setObjectName("selectCsLineButton")
        self.horizontalLayout_7.addWidget(self.selectCsLineButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.helpBox = QtWidgets.QTextBrowser(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBox.sizePolicy().hasHeightForWidth())
        self.helpBox.setSizePolicy(sizePolicy)
        self.helpBox.setMaximumSize(QtCore.QSize(320, 16777215))
        self.helpBox.setObjectName("helpBox")
        self.horizontalLayout_2.addWidget(self.helpBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logText = QtWidgets.QTextBrowser(self.tab_2)
        self.logText.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.logText.setReadOnly(True)
        self.logText.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.logText.setOpenExternalLinks(True)
        self.logText.setObjectName("logText")
        self.horizontalLayout_3.addWidget(self.logText)
        self.Tabs.addTab(self.tab_2, "")
        self.verticalLayout_11.addWidget(self.Tabs)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.progressBar = QtWidgets.QProgressBar(MaskMakerDialogBase)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_10.addWidget(self.progressBar)
        self.cancelButton = QtWidgets.QPushButton(MaskMakerDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_10.addWidget(self.cancelButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.warningLabel = QtWidgets.QLabel(MaskMakerDialogBase)
        self.warningLabel.setText("")
        self.warningLabel.setWordWrap(True)
        self.warningLabel.setObjectName("warningLabel")
        self.horizontalLayout_12.addWidget(self.warningLabel)
        self.runButton = QtWidgets.QPushButton(MaskMakerDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_12.addWidget(self.runButton)
        self.closeButton = QtWidgets.QPushButton(MaskMakerDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_12.addWidget(self.closeButton)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)

        self.retranslateUi(MaskMakerDialogBase)
        self.Tabs.setCurrentIndex(0)
        self.closeButton.clicked.connect(MaskMakerDialogBase.close)
        QtCore.QMetaObject.connectSlotsByName(MaskMakerDialogBase)

    def retranslateUi(self, MaskMakerDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MaskMakerDialogBase.setWindowTitle(_translate("MaskMakerDialogBase", "Paleogeography - Mask preparation"))
        self.groupBox.setTitle(_translate("MaskMakerDialogBase", "Shallow seas"))
        self.label_4.setText(_translate("MaskMakerDialogBase", "Polygon layer"))
        self.selectSsButton.setText(_translate("MaskMakerDialogBase", "..."))
        self.label_9.setText(_translate("MaskMakerDialogBase", "Polyline  layer"))
        self.selectSsLineButton.setText(_translate("MaskMakerDialogBase", "..."))
        self.groupBox_4.setTitle(_translate("MaskMakerDialogBase", "Output file path:"))
        self.groupBox_2.setTitle(_translate("MaskMakerDialogBase", "Coastlines"))
        self.label_5.setText(_translate("MaskMakerDialogBase", "Polygon layer"))
        self.selectCoastButton.setText(_translate("MaskMakerDialogBase", "..."))
        self.label_11.setText(_translate("MaskMakerDialogBase", "Polyline  layer"))
        self.selectCoastLineButton.setText(_translate("MaskMakerDialogBase", "..."))
        self.groupBox_3.setTitle(_translate("MaskMakerDialogBase", "Continental shelves"))
        self.label_8.setText(_translate("MaskMakerDialogBase", "Polygon layer"))
        self.selectCsButton.setText(_translate("MaskMakerDialogBase", "..."))
        self.label_10.setText(_translate("MaskMakerDialogBase", "Polyline  layer"))
        self.selectCsLineButton.setText(_translate("MaskMakerDialogBase", "..."))
        self.helpBox.setPlaceholderText(_translate("MaskMakerDialogBase", "Help shall be displayed here."))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MaskMakerDialogBase", "Parameters"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MaskMakerDialogBase", "Log"))
        self.cancelButton.setText(_translate("MaskMakerDialogBase", "Cancel"))
        self.runButton.setText(_translate("MaskMakerDialogBase", "Run"))
        self.closeButton.setText(_translate("MaskMakerDialogBase", "Close"))


from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
