# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mask_maker_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DEMBuilderDialogBase(object):
    def setupUi(self, DEMBuilderDialogBase):
        DEMBuilderDialogBase.setObjectName("DEMBuilderDialogBase")
        DEMBuilderDialogBase.resize(645, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DEMBuilderDialogBase.sizePolicy().hasHeightForWidth())
        DEMBuilderDialogBase.setSizePolicy(sizePolicy)
        self.button_box = QtWidgets.QDialogButtonBox(DEMBuilderDialogBase)
        self.button_box.setGeometry(QtCore.QRect(250, 540, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label_7 = QtWidgets.QLabel(DEMBuilderDialogBase)
        self.label_7.setGeometry(QtCore.QRect(30, 480, 91, 16))
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(DEMBuilderDialogBase)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 480, 421, 22))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputFile = QgsFileWidget(self.verticalLayoutWidget)
        self.outputFile.setObjectName("outputFile")
        self.verticalLayout.addWidget(self.outputFile)
        self.groupBox = QtWidgets.QGroupBox(DEMBuilderDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(20, 320, 601, 141))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 30, 421, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.selectSsMask = QgsMapLayerComboBox(self.layoutWidget)
        self.selectSsMask.setAllowEmptyLayer(True)
        self.selectSsMask.setShowCrs(True)
        self.selectSsMask.setExcludedProviders(['"gdal"'])
        self.selectSsMask.setObjectName("selectSsMask")
        self.horizontalLayout_4.addWidget(self.selectSsMask)
        self.selectTopoButton_2 = QtWidgets.QToolButton(self.layoutWidget)
        self.selectTopoButton_2.setObjectName("selectTopoButton_2")
        self.horizontalLayout_4.addWidget(self.selectTopoButton_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.label_4.setObjectName("label_4")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(150, 90, 421, 27))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectSsMaskLine = QgsMapLayerComboBox(self.layoutWidget_3)
        self.selectSsMaskLine.setAllowEmptyLayer(True)
        self.selectSsMaskLine.setShowCrs(True)
        self.selectSsMaskLine.setExcludedProviders(['"gdal"'])
        self.selectSsMaskLine.setObjectName("selectSsMaskLine")
        self.horizontalLayout_6.addWidget(self.selectSsMaskLine)
        self.selectTopoButton_4 = QtWidgets.QToolButton(self.layoutWidget_3)
        self.selectTopoButton_4.setObjectName("selectTopoButton_4")
        self.horizontalLayout_6.addWidget(self.selectTopoButton_4)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 121, 17))
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(DEMBuilderDialogBase)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 170, 601, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_8.setObjectName("label_8")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(150, 30, 421, 27))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.selectCshMask = QgsMapLayerComboBox(self.layoutWidget_2)
        self.selectCshMask.setAllowEmptyLayer(True)
        self.selectCshMask.setShowCrs(True)
        self.selectCshMask.setExcludedProviders(['"gdal"'])
        self.selectCshMask.setObjectName("selectCshMask")
        self.horizontalLayout_5.addWidget(self.selectCshMask)
        self.selectTopoButton_3 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.selectTopoButton_3.setObjectName("selectTopoButton_3")
        self.horizontalLayout_5.addWidget(self.selectTopoButton_3)
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_7.setGeometry(QtCore.QRect(150, 90, 421, 27))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.selectCshMaskLine = QgsMapLayerComboBox(self.layoutWidget_7)
        self.selectCshMaskLine.setAllowEmptyLayer(True)
        self.selectCshMaskLine.setShowCrs(True)
        self.selectCshMaskLine.setExcludedProviders(['"gdal"'])
        self.selectCshMaskLine.setObjectName("selectCshMaskLine")
        self.horizontalLayout_7.addWidget(self.selectCshMaskLine)
        self.selectTopoButton_5 = QtWidgets.QToolButton(self.layoutWidget_7)
        self.selectTopoButton_5.setObjectName("selectTopoButton_5")
        self.horizontalLayout_7.addWidget(self.selectTopoButton_5)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 131, 17))
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtWidgets.QGroupBox(DEMBuilderDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 601, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(150, 30, 421, 27))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.selectCoastlineMask = QgsMapLayerComboBox(self.layoutWidget_4)
        self.selectCoastlineMask.setAllowEmptyLayer(True)
        self.selectCoastlineMask.setShowCrs(True)
        self.selectCoastlineMask.setExcludedProviders(['"gdal"'])
        self.selectCoastlineMask.setObjectName("selectCoastlineMask")
        self.horizontalLayout_8.addWidget(self.selectCoastlineMask)
        self.selectTopoButton_6 = QtWidgets.QToolButton(self.layoutWidget_4)
        self.selectTopoButton_6.setObjectName("selectTopoButton_6")
        self.horizontalLayout_8.addWidget(self.selectTopoButton_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.label_5.setObjectName("label_5")
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(150, 90, 421, 27))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.selectCoastlineMaskLine = QgsMapLayerComboBox(self.layoutWidget_5)
        self.selectCoastlineMaskLine.setAllowEmptyLayer(True)
        self.selectCoastlineMaskLine.setShowCrs(True)
        self.selectCoastlineMaskLine.setExcludedProviders(['"gdal"'])
        self.selectCoastlineMaskLine.setObjectName("selectCoastlineMaskLine")
        self.horizontalLayout_9.addWidget(self.selectCoastlineMaskLine)
        self.selectTopoButton_7 = QtWidgets.QToolButton(self.layoutWidget_5)
        self.selectTopoButton_7.setObjectName("selectTopoButton_7")
        self.horizontalLayout_9.addWidget(self.selectTopoButton_7)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 121, 17))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(DEMBuilderDialogBase)
        self.button_box.accepted.connect(DEMBuilderDialogBase.accept)
        self.button_box.rejected.connect(DEMBuilderDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(DEMBuilderDialogBase)

    def retranslateUi(self, DEMBuilderDialogBase):
        _translate = QtCore.QCoreApplication.translate
        DEMBuilderDialogBase.setWindowTitle(_translate("DEMBuilderDialogBase", "Paleogeography"))
        self.label_7.setText(_translate("DEMBuilderDialogBase", "Output directory"))
        self.groupBox.setTitle(_translate("DEMBuilderDialogBase", "Shallow sea masks"))
        self.selectTopoButton_2.setText(_translate("DEMBuilderDialogBase", "..."))
        self.label_4.setText(_translate("DEMBuilderDialogBase", "Polygon layer"))
        self.selectTopoButton_4.setText(_translate("DEMBuilderDialogBase", "..."))
        self.label_9.setText(_translate("DEMBuilderDialogBase", "Polyline  layer"))
        self.groupBox_3.setTitle(_translate("DEMBuilderDialogBase", "Continental Shelves masks"))
        self.label_8.setText(_translate("DEMBuilderDialogBase", "Polygon layer"))
        self.selectTopoButton_3.setText(_translate("DEMBuilderDialogBase", "..."))
        self.selectTopoButton_5.setText(_translate("DEMBuilderDialogBase", "..."))
        self.label_10.setText(_translate("DEMBuilderDialogBase", "Polyline  layer"))
        self.groupBox_2.setTitle(_translate("DEMBuilderDialogBase", "Coastlines"))
        self.selectTopoButton_6.setText(_translate("DEMBuilderDialogBase", "..."))
        self.label_5.setText(_translate("DEMBuilderDialogBase", "Polygon layer"))
        self.selectTopoButton_7.setText(_translate("DEMBuilderDialogBase", "..."))
        self.label_11.setText(_translate("DEMBuilderDialogBase", "Polyline  layer"))

from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
