# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paleoshorelines_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_PaleocoastlinesDialogBase(object):
    def setupUi(self, PaleocoastlinesDialogBase):
        PaleocoastlinesDialogBase.setObjectName("PaleocoastlinesDialogBase")
        PaleocoastlinesDialogBase.resize(880, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PaleocoastlinesDialogBase.sizePolicy().hasHeightForWidth())
        PaleocoastlinesDialogBase.setSizePolicy(sizePolicy)
        PaleocoastlinesDialogBase.setMinimumSize(QtCore.QSize(400, 200))
        PaleocoastlinesDialogBase.setAutoFillBackground(True)
        PaleocoastlinesDialogBase.setSizeGripEnabled(True)
        PaleocoastlinesDialogBase.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(PaleocoastlinesDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(PaleocoastlinesDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tabs.setUsesScrollButtons(False)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 498, 366))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.baseTopoBox = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        self.baseTopoBox.setObjectName("baseTopoBox")
        self.horizontalLayout_2.addWidget(self.baseTopoBox)
        self.selectTopoBaseButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.selectTopoBaseButton.setObjectName("selectTopoBaseButton")
        self.horizontalLayout_2.addWidget(self.selectTopoBaseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.masksBox = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        self.masksBox.setObjectName("masksBox")
        self.horizontalLayout_3.addWidget(self.masksBox)
        self.selectMasksButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.selectMasksButton.setObjectName("selectMasksButton")
        self.horizontalLayout_3.addWidget(self.selectMasksButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 6, -1, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.interpolateCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.interpolateCheckBox.setObjectName("interpolateCheckBox")
        self.horizontalLayout_4.addWidget(self.interpolateCheckBox)
        self.rescaleCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.rescaleCheckBox.setObjectName("rescaleCheckBox")
        self.horizontalLayout_4.addWidget(self.rescaleCheckBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.maxElevSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.maxElevSpinBox.setMinimum(-1.0)
        self.maxElevSpinBox.setMaximum(2000.0)
        self.maxElevSpinBox.setProperty("value", 2.0)
        self.maxElevSpinBox.setObjectName("maxElevSpinBox")
        self.verticalLayout_4.addWidget(self.maxElevSpinBox)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.maxDepthSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.maxDepthSpinBox.setMinimum(-1000.0)
        self.maxDepthSpinBox.setMaximum(1.0)
        self.maxDepthSpinBox.setProperty("value", -5.0)
        self.maxDepthSpinBox.setObjectName("maxDepthSpinBox")
        self.verticalLayout_4.addWidget(self.maxDepthSpinBox)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_3.addWidget(self.outputLabel)
        self.outputPath = QgsFileWidget(self.scrollAreaWidgetContents)
        self.outputPath.setObjectName("outputPath")
        self.verticalLayout_3.addWidget(self.outputPath)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.helpBox = QtWidgets.QTextBrowser(self.tab)
        self.helpBox.setMaximumSize(QtCore.QSize(320, 16777215))
        self.helpBox.setObjectName("helpBox")
        self.horizontalLayout.addWidget(self.helpBox)
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.logText = QtWidgets.QTextBrowser(self.tab_2)
        self.logText.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.logText.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByKeyboard | QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextBrowserInteraction | QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.logText.setOpenExternalLinks(True)
        self.logText.setObjectName("logText")
        self.gridLayout_11.addWidget(self.logText, 0, 0, 1, 1)
        self.Tabs.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.progressBar = QtWidgets.QProgressBar(PaleocoastlinesDialogBase)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_10.addWidget(self.progressBar)
        self.cancelButton = QtWidgets.QPushButton(PaleocoastlinesDialogBase)
        self.cancelButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_10.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.warningLabel = QtWidgets.QLabel(PaleocoastlinesDialogBase)
        self.warningLabel.setText("")
        self.warningLabel.setWordWrap(True)
        self.warningLabel.setObjectName("warningLabel")
        self.horizontalLayout_8.addWidget(self.warningLabel)
        self.runButton = QtWidgets.QPushButton(PaleocoastlinesDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_8.addWidget(self.runButton)
        self.closeButton = QtWidgets.QPushButton(PaleocoastlinesDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_8.addWidget(self.closeButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)

        self.retranslateUi(PaleocoastlinesDialogBase)
        self.Tabs.setCurrentIndex(0)
        self.closeButton.clicked.connect(PaleocoastlinesDialogBase.hide)
        QtCore.QMetaObject.connectSlotsByName(PaleocoastlinesDialogBase)
        PaleocoastlinesDialogBase.setTabOrder(self.runButton, self.Tabs)
        PaleocoastlinesDialogBase.setTabOrder(self.Tabs, self.helpBox)
        PaleocoastlinesDialogBase.setTabOrder(self.helpBox, self.closeButton)
        PaleocoastlinesDialogBase.setTabOrder(self.closeButton, self.cancelButton)

    def retranslateUi(self, PaleocoastlinesDialogBase):
        _translate = QtCore.QCoreApplication.translate
        PaleocoastlinesDialogBase.setWindowTitle(
            _translate("PaleocoastlinesDialogBase", "Paleogeography - Paleoshorelines and smoothing"))
        self.label.setText(_translate("PaleocoastlinesDialogBase", "Raster to be modified (Input):"))
        self.selectTopoBaseButton.setText(_translate("PaleocoastlinesDialogBase", "..."))
        self.label_2.setText(_translate("PaleocoastlinesDialogBase", "Rotated paleoshorelines:"))
        self.selectMasksButton.setText(_translate("PaleocoastlinesDialogBase", "..."))
        self.label_5.setText(_translate("PaleocoastlinesDialogBase", "Modification mode:"))
        self.interpolateCheckBox.setText(_translate("PaleocoastlinesDialogBase", "Interpolation"))
        self.rescaleCheckBox.setText(_translate("PaleocoastlinesDialogBase", "Rescaling"))
        self.label_4.setText(_translate("PaleocoastlinesDialogBase", "Maximum elevation of the emerged area (in m):"))
        self.label_3.setText(_translate("PaleocoastlinesDialogBase", "Maximum depth of the submerged area (in m):"))
        self.outputLabel.setText(_translate("PaleocoastlinesDialogBase", "Output file path:"))
        self.helpBox.setPlaceholderText(
            _translate("PaleocoastlinesDialogBase", "Here we shall see the help text for the tool. "))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("PaleocoastlinesDialogBase", "Parameters"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("PaleocoastlinesDialogBase", "Log"))
        self.cancelButton.setText(_translate("PaleocoastlinesDialogBase", "Cancel"))
        self.runButton.setText(_translate("PaleocoastlinesDialogBase", "Run"))
        self.closeButton.setText(_translate("PaleocoastlinesDialogBase", "Close"))


from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
