# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'std_proc_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_FillSmoothDialogBase(object):
    def setupUi(self, FillSmoothDialogBase):
        FillSmoothDialogBase.setObjectName("FillSmoothDialogBase")
        FillSmoothDialogBase.resize(880, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FillSmoothDialogBase.sizePolicy().hasHeightForWidth())
        FillSmoothDialogBase.setSizePolicy(sizePolicy)
        FillSmoothDialogBase.setMinimumSize(QtCore.QSize(400, 200))
        FillSmoothDialogBase.setAutoFillBackground(True)
        FillSmoothDialogBase.setSizeGripEnabled(True)
        FillSmoothDialogBase.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(FillSmoothDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(FillSmoothDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tabs.setUsesScrollButtons(False)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 497))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.fillingTypeBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.fillingTypeBox.setObjectName("fillingTypeBox")
        self.verticalLayout_4.addWidget(self.fillingTypeBox)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.baseRasterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.baseRasterLabel.setObjectName("baseRasterLabel")
        self.verticalLayout.addWidget(self.baseRasterLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.baseTopoBox = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        self.baseTopoBox.setObjectName("baseTopoBox")
        self.horizontalLayout_2.addWidget(self.baseTopoBox)
        self.selectTopoBaseButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.selectTopoBaseButton.setObjectName("selectTopoBaseButton")
        self.horizontalLayout_2.addWidget(self.selectTopoBaseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.iceTopoLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.iceTopoLabel.setObjectName("iceTopoLabel")
        self.verticalLayout_6.addWidget(self.iceTopoLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectIceTopoBox = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        self.selectIceTopoBox.setObjectName("selectIceTopoBox")
        self.horizontalLayout_6.addWidget(self.selectIceTopoBox)
        self.selectIceTopoButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.selectIceTopoButton.setObjectName("selectIceTopoButton")
        self.horizontalLayout_6.addWidget(self.selectIceTopoButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.copyFromRasterLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.copyFromRasterLabel.setObjectName("copyFromRasterLabel")
        self.verticalLayout_5.addWidget(self.copyFromRasterLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.copyFromRasterBox = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        self.copyFromRasterBox.setObjectName("copyFromRasterBox")
        self.horizontalLayout_5.addWidget(self.copyFromRasterBox)
        self.selectCopyFromRasterButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.selectCopyFromRasterButton.setObjectName("selectCopyFromRasterButton")
        self.horizontalLayout_5.addWidget(self.selectCopyFromRasterButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.masksBoxLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.masksBoxLabel.setObjectName("masksBoxLabel")
        self.verticalLayout_2.addWidget(self.masksBoxLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.masksBox = QgsMapLayerComboBox(self.scrollAreaWidgetContents)
        self.masksBox.setObjectName("masksBox")
        self.horizontalLayout_3.addWidget(self.masksBox)
        self.selectMasksButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.selectMasksButton.setObjectName("selectMasksButton")
        self.horizontalLayout_3.addWidget(self.selectMasksButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.masksFromCoastCheckBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.masksFromCoastCheckBox.setObjectName("masksFromCoastCheckBox")
        self.verticalLayout_8.addWidget(self.masksFromCoastCheckBox)
        self.iceAmountLayout = QtWidgets.QHBoxLayout()
        self.iceAmountLayout.setContentsMargins(-1, 0, -1, 0)
        self.iceAmountLayout.setObjectName("iceAmountLayout")
        self.iceAmountLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.iceAmountLabel.setObjectName("iceAmountLabel")
        self.iceAmountLayout.addWidget(self.iceAmountLabel)
        self.iceAmountSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.iceAmountSpinBox.setMaximum(100)
        self.iceAmountSpinBox.setProperty("value", 100)
        self.iceAmountSpinBox.setObjectName("iceAmountSpinBox")
        self.iceAmountLayout.addWidget(self.iceAmountSpinBox)
        self.verticalLayout_8.addLayout(self.iceAmountLayout)
        self.smoothingLayout = QtWidgets.QVBoxLayout()
        self.smoothingLayout.setObjectName("smoothingLayout")
        self.smoothingBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.smoothingBox.setObjectName("smoothingBox")
        self.smoothingLayout.addWidget(self.smoothingBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.smoothingLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.smoothingLabel.setObjectName("smoothingLabel")
        self.horizontalLayout_4.addWidget(self.smoothingLabel)
        self.smFactorSpinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.smFactorSpinBox.setMinimum(1)
        self.smFactorSpinBox.setMaximum(5)
        self.smFactorSpinBox.setObjectName("smFactorSpinBox")
        self.horizontalLayout_4.addWidget(self.smFactorSpinBox)
        self.smoothingLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.smoothingLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_3.addWidget(self.outputLabel)
        self.outputPath = QgsFileWidget(self.scrollAreaWidgetContents)
        self.outputPath.setObjectName("outputPath")
        self.verticalLayout_3.addWidget(self.outputPath)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.helpBox = QtWidgets.QTextBrowser(self.tab)
        self.helpBox.setMaximumSize(QtCore.QSize(320, 16777215))
        self.helpBox.setObjectName("helpBox")
        self.horizontalLayout.addWidget(self.helpBox)
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.logText = QtWidgets.QTextBrowser(self.tab_2)
        self.logText.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.logText.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByKeyboard | QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextBrowserInteraction | QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.logText.setOpenExternalLinks(True)
        self.logText.setObjectName("logText")
        self.gridLayout_11.addWidget(self.logText, 0, 0, 1, 1)
        self.Tabs.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.progressBar = QtWidgets.QProgressBar(FillSmoothDialogBase)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_10.addWidget(self.progressBar)
        self.cancelButton = QtWidgets.QPushButton(FillSmoothDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_10.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.warningLabel = QtWidgets.QLabel(FillSmoothDialogBase)
        self.warningLabel.setText("")
        self.warningLabel.setWordWrap(True)
        self.warningLabel.setObjectName("warningLabel")
        self.horizontalLayout_8.addWidget(self.warningLabel)
        self.runButton = QtWidgets.QPushButton(FillSmoothDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_8.addWidget(self.runButton)
        self.closeButton = QtWidgets.QPushButton(FillSmoothDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_8.addWidget(self.closeButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)

        self.retranslateUi(FillSmoothDialogBase)
        self.Tabs.setCurrentIndex(0)
        self.closeButton.clicked.connect(FillSmoothDialogBase.hide)
        QtCore.QMetaObject.connectSlotsByName(FillSmoothDialogBase)
        FillSmoothDialogBase.setTabOrder(self.runButton, self.Tabs)
        FillSmoothDialogBase.setTabOrder(self.Tabs, self.helpBox)
        FillSmoothDialogBase.setTabOrder(self.helpBox, self.closeButton)
        FillSmoothDialogBase.setTabOrder(self.closeButton, self.cancelButton)

    def retranslateUi(self, FillSmoothDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FillSmoothDialogBase.setWindowTitle(_translate("FillSmoothDialogBase",
                                                       "Paleogeography - Standard processing tools (Interpolation, smoothing etc.)"))
        self.label_3.setText(_translate("FillSmoothDialogBase", "How do you want to process your DEM?"))
        self.baseRasterLabel.setText(_translate("FillSmoothDialogBase", "Raster to be modified:"))
        self.selectTopoBaseButton.setText(_translate("FillSmoothDialogBase", "..."))
        self.iceTopoLabel.setText(_translate("FillSmoothDialogBase", "Ice topography raster layer:"))
        self.selectIceTopoButton.setText(_translate("FillSmoothDialogBase", "..."))
        self.copyFromRasterLabel.setText(_translate("FillSmoothDialogBase", "Select the  raster to copy values from:"))
        self.selectCopyFromRasterButton.setText(_translate("FillSmoothDialogBase", "..."))
        self.masksBoxLabel.setText(_translate("FillSmoothDialogBase", "Masks:"))
        self.selectMasksButton.setText(_translate("FillSmoothDialogBase", "..."))
        self.masksFromCoastCheckBox.setText(_translate("FillSmoothDialogBase", "Get the masks from coastlines."))
        self.iceAmountLabel.setText(_translate("FillSmoothDialogBase", "Amount of the ice to be removed (in % ):"))
        self.smoothingBox.setText(_translate("FillSmoothDialogBase", "Smooth resulting raster."))
        self.smoothingLabel.setText(_translate("FillSmoothDialogBase", "Smoothing factor(in grid cells):"))
        self.outputLabel.setText(_translate("FillSmoothDialogBase", "Output file path:"))
        self.helpBox.setPlaceholderText(
            _translate("FillSmoothDialogBase", "Here we shall see the help text for the tool. "))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("FillSmoothDialogBase", "Parameters"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("FillSmoothDialogBase", "Log"))
        self.cancelButton.setText(_translate("FillSmoothDialogBase", "Cancel"))
        self.runButton.setText(_translate("FillSmoothDialogBase", "Run"))
        self.closeButton.setText(_translate("FillSmoothDialogBase", "Close"))


from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
