# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'topo_modifier_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtWidgets


class Ui_TopoModifierDialogBase(object):
    def setupUi(self, TopoModifierDialogBase):
        TopoModifierDialogBase.setObjectName("TopoModifierDialogBase")
        TopoModifierDialogBase.resize(880, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TopoModifierDialogBase.sizePolicy().hasHeightForWidth())
        TopoModifierDialogBase.setSizePolicy(sizePolicy)
        TopoModifierDialogBase.setMinimumSize(QtCore.QSize(400, 200))
        TopoModifierDialogBase.setAutoFillBackground(True)
        TopoModifierDialogBase.setSizeGripEnabled(True)
        TopoModifierDialogBase.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(TopoModifierDialogBase)
        self.gridLayout.setObjectName("gridLayout")
        self.Tabs = QtWidgets.QTabWidget(TopoModifierDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tabs.setUsesScrollButtons(False)
        self.Tabs.setObjectName("Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -336, 518, 923))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.baseTopoBox = QgsMapLayerComboBox(self.groupBox)
        self.baseTopoBox.setObjectName("baseTopoBox")
        self.horizontalLayout.addWidget(self.baseTopoBox)
        self.selectTopoBaseButton = QtWidgets.QToolButton(self.groupBox)
        self.selectTopoBaseButton.setObjectName("selectTopoBaseButton")
        self.horizontalLayout.addWidget(self.selectTopoBaseButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.masksBox = QgsMapLayerComboBox(self.groupBox)
        self.masksBox.setObjectName("masksBox")
        self.horizontalLayout_2.addWidget(self.masksBox)
        self.selectMasksButton = QtWidgets.QToolButton(self.groupBox)
        self.selectMasksButton.setObjectName("selectMasksButton")
        self.horizontalLayout_2.addWidget(self.selectMasksButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.useAllMasksBox = QtWidgets.QCheckBox(self.groupBox)
        self.useAllMasksBox.setObjectName("useAllMasksBox")
        self.verticalLayout_2.addWidget(self.useAllMasksBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.maskNameField = QgsFieldComboBox(self.groupBox)
        self.maskNameField.setObjectName("maskNameField")
        self.horizontalLayout_3.addWidget(self.maskNameField)
        self.maskNameText = QtWidgets.QLineEdit(self.groupBox)
        self.maskNameText.setObjectName("maskNameText")
        self.horizontalLayout_3.addWidget(self.maskNameText)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.minMaxCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.minMaxCheckBox.setObjectName("minMaxCheckBox")
        self.verticalLayout_8.addWidget(self.minMaxCheckBox)
        self.formulaCheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.formulaCheckBox.setObjectName("formulaCheckBox")
        self.verticalLayout_8.addWidget(self.formulaCheckBox)
        self.formulaGroupBox = QgsCollapsibleGroupBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formulaGroupBox.sizePolicy().hasHeightForWidth())
        self.formulaGroupBox.setSizePolicy(sizePolicy)
        self.formulaGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.formulaGroupBox.setAutoFillBackground(False)
        self.formulaGroupBox.setProperty("collapsed", False)
        self.formulaGroupBox.setProperty("saveCollapsedState", True)
        self.formulaGroupBox.setObjectName("formulaGroupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.formulaGroupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.formulaGroupBox)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.formulaField = QgsFieldComboBox(self.formulaGroupBox)
        self.formulaField.setProperty("allowEmptyFieldName", True)
        self.formulaField.setObjectName("formulaField")
        self.horizontalLayout_13.addWidget(self.formulaField)
        self.formulaText = QtWidgets.QLineEdit(self.formulaGroupBox)
        self.formulaText.setObjectName("formulaText")
        self.horizontalLayout_13.addWidget(self.formulaText)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.min_maxValueCheckBox = QtWidgets.QCheckBox(self.formulaGroupBox)
        self.min_maxValueCheckBox.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.min_maxValueCheckBox.setObjectName("min_maxValueCheckBox")
        self.verticalLayout_7.addWidget(self.min_maxValueCheckBox)
        self.boundingValuesGroupBox = QtWidgets.QGroupBox(self.formulaGroupBox)
        self.boundingValuesGroupBox.setObjectName("boundingValuesGroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.boundingValuesGroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.minMaxValuesFromAttrCheckBox = QtWidgets.QCheckBox(self.boundingValuesGroupBox)
        self.minMaxValuesFromAttrCheckBox.setObjectName("minMaxValuesFromAttrCheckBox")
        self.verticalLayout_6.addWidget(self.minMaxValuesFromAttrCheckBox)
        self.minMaxValuesFromSpinCheckBox = QtWidgets.QCheckBox(self.boundingValuesGroupBox)
        self.minMaxValuesFromSpinCheckBox.setObjectName("minMaxValuesFromSpinCheckBox")
        self.verticalLayout_6.addWidget(self.minMaxValuesFromSpinCheckBox)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.minValueLabel = QtWidgets.QLabel(self.boundingValuesGroupBox)
        self.minValueLabel.setObjectName("minValueLabel")
        self.horizontalLayout_12.addWidget(self.minValueLabel)
        self.maxValueLabel = QtWidgets.QLabel(self.boundingValuesGroupBox)
        self.maxValueLabel.setObjectName("maxValueLabel")
        self.horizontalLayout_12.addWidget(self.maxValueLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.minValueField = QgsFieldComboBox(self.boundingValuesGroupBox)
        self.minValueField.setObjectName("minValueField")
        self.horizontalLayout_11.addWidget(self.minValueField)
        self.maxValueField = QgsFieldComboBox(self.boundingValuesGroupBox)
        self.maxValueField.setObjectName("maxValueField")
        self.horizontalLayout_11.addWidget(self.maxValueField)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.minValueSpin = QtWidgets.QSpinBox(self.boundingValuesGroupBox)
        self.minValueSpin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.minValueSpin.setAcceptDrops(False)
        self.minValueSpin.setToolTipDuration(-1)
        self.minValueSpin.setMinimum(-11000)
        self.minValueSpin.setMaximum(11000)
        self.minValueSpin.setProperty("value", 0)
        self.minValueSpin.setObjectName("minValueSpin")
        self.horizontalLayout_7.addWidget(self.minValueSpin)
        self.maxValueSpin = QtWidgets.QSpinBox(self.boundingValuesGroupBox)
        self.maxValueSpin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.maxValueSpin.setMinimum(-11000)
        self.maxValueSpin.setMaximum(11000)
        self.maxValueSpin.setObjectName("maxValueSpin")
        self.horizontalLayout_7.addWidget(self.maxValueSpin)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_7.addWidget(self.boundingValuesGroupBox)
        self.verticalLayout_8.addWidget(self.formulaGroupBox)
        self.minMaxGroupBox = QgsCollapsibleGroupBox(self.groupBox_3)
        self.minMaxGroupBox.setObjectName("minMaxGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.minMaxGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.minMaxFromAttrCheckBox = QtWidgets.QCheckBox(self.minMaxGroupBox)
        self.minMaxFromAttrCheckBox.setObjectName("minMaxFromAttrCheckBox")
        self.verticalLayout_5.addWidget(self.minMaxFromAttrCheckBox)
        self.label_5 = QtWidgets.QLabel(self.minMaxGroupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minField = QgsFieldComboBox(self.minMaxGroupBox)
        self.minField.setObjectName("minField")
        self.horizontalLayout_5.addWidget(self.minField)
        self.minSpin = QtWidgets.QSpinBox(self.minMaxGroupBox)
        self.minSpin.setMinimum(-11000)
        self.minSpin.setMaximum(11000)
        self.minSpin.setSingleStep(100)
        self.minSpin.setObjectName("minSpin")
        self.horizontalLayout_5.addWidget(self.minSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.label_6 = QtWidgets.QLabel(self.minMaxGroupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.maxField = QgsFieldComboBox(self.minMaxGroupBox)
        self.maxField.setObjectName("maxField")
        self.horizontalLayout_6.addWidget(self.maxField)
        self.maxSpin = QtWidgets.QSpinBox(self.minMaxGroupBox)
        self.maxSpin.setMinimum(-11000)
        self.maxSpin.setMaximum(11000)
        self.maxSpin.setSingleStep(100)
        self.maxSpin.setObjectName("maxSpin")
        self.horizontalLayout_6.addWidget(self.maxSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8.addWidget(self.minMaxGroupBox)
        self.verticalLayout_9.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputLaber = QtWidgets.QLabel(self.groupBox_2)
        self.outputLaber.setObjectName("outputLaber")
        self.verticalLayout.addWidget(self.outputLaber)
        self.outputPath = QgsFileWidget(self.groupBox_2)
        self.outputPath.setObjectName("outputPath")
        self.verticalLayout.addWidget(self.outputPath)
        self.verticalLayout_9.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_14.addWidget(self.scrollArea)
        self.helpBox = QtWidgets.QTextBrowser(self.tab)
        self.helpBox.setMaximumSize(QtCore.QSize(320, 16777215))
        self.helpBox.setObjectName("helpBox")
        self.horizontalLayout_14.addWidget(self.helpBox)
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.logText = QtWidgets.QTextBrowser(self.tab_2)
        self.logText.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.logText.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByKeyboard | QtCore.Qt.LinksAccessibleByMouse | QtCore.Qt.TextBrowserInteraction | QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.logText.setOpenExternalLinks(True)
        self.logText.setObjectName("logText")
        self.gridLayout_11.addWidget(self.logText, 0, 0, 1, 1)
        self.Tabs.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.progressBar = QtWidgets.QProgressBar(TopoModifierDialogBase)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_10.addWidget(self.progressBar)
        self.cancelButton = QtWidgets.QPushButton(TopoModifierDialogBase)
        self.cancelButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_10.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.warningLabel = QtWidgets.QLabel(TopoModifierDialogBase)
        self.warningLabel.setText("")
        self.warningLabel.setWordWrap(True)
        self.warningLabel.setObjectName("warningLabel")
        self.horizontalLayout_8.addWidget(self.warningLabel)
        self.runButton = QtWidgets.QPushButton(TopoModifierDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_8.addWidget(self.runButton)
        self.closeButton = QtWidgets.QPushButton(TopoModifierDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_8.addWidget(self.closeButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)

        self.retranslateUi(TopoModifierDialogBase)
        self.Tabs.setCurrentIndex(0)
        self.closeButton.clicked.connect(TopoModifierDialogBase.hide)
        QtCore.QMetaObject.connectSlotsByName(TopoModifierDialogBase)
        TopoModifierDialogBase.setTabOrder(self.runButton, self.baseTopoBox)
        TopoModifierDialogBase.setTabOrder(self.baseTopoBox, self.Tabs)
        TopoModifierDialogBase.setTabOrder(self.Tabs, self.scrollArea)
        TopoModifierDialogBase.setTabOrder(self.scrollArea, self.closeButton)
        TopoModifierDialogBase.setTabOrder(self.closeButton, self.selectTopoBaseButton)
        TopoModifierDialogBase.setTabOrder(self.selectTopoBaseButton, self.masksBox)
        TopoModifierDialogBase.setTabOrder(self.masksBox, self.selectMasksButton)
        TopoModifierDialogBase.setTabOrder(self.selectMasksButton, self.maskNameField)
        TopoModifierDialogBase.setTabOrder(self.maskNameField, self.maskNameText)
        TopoModifierDialogBase.setTabOrder(self.maskNameText, self.minMaxCheckBox)
        TopoModifierDialogBase.setTabOrder(self.minMaxCheckBox, self.formulaCheckBox)
        TopoModifierDialogBase.setTabOrder(self.formulaCheckBox, self.formulaGroupBox)
        TopoModifierDialogBase.setTabOrder(self.formulaGroupBox, self.formulaField)
        TopoModifierDialogBase.setTabOrder(self.formulaField, self.formulaText)
        TopoModifierDialogBase.setTabOrder(self.formulaText, self.min_maxValueCheckBox)
        TopoModifierDialogBase.setTabOrder(self.min_maxValueCheckBox, self.minMaxValuesFromAttrCheckBox)
        TopoModifierDialogBase.setTabOrder(self.minMaxValuesFromAttrCheckBox, self.minMaxValuesFromSpinCheckBox)
        TopoModifierDialogBase.setTabOrder(self.minMaxValuesFromSpinCheckBox, self.minValueField)
        TopoModifierDialogBase.setTabOrder(self.minValueField, self.maxValueField)
        TopoModifierDialogBase.setTabOrder(self.maxValueField, self.minValueSpin)
        TopoModifierDialogBase.setTabOrder(self.minValueSpin, self.maxValueSpin)
        TopoModifierDialogBase.setTabOrder(self.maxValueSpin, self.minMaxGroupBox)
        TopoModifierDialogBase.setTabOrder(self.minMaxGroupBox, self.minMaxFromAttrCheckBox)
        TopoModifierDialogBase.setTabOrder(self.minMaxFromAttrCheckBox, self.minField)
        TopoModifierDialogBase.setTabOrder(self.minField, self.minSpin)
        TopoModifierDialogBase.setTabOrder(self.minSpin, self.maxField)
        TopoModifierDialogBase.setTabOrder(self.maxField, self.maxSpin)
        TopoModifierDialogBase.setTabOrder(self.maxSpin, self.cancelButton)

    def retranslateUi(self, TopoModifierDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TopoModifierDialogBase.setWindowTitle(
            _translate("TopoModifierDialogBase", "Paleogeography - Topography modification"))
        self.groupBox.setTitle(_translate("TopoModifierDialogBase", "Input layers"))
        self.label.setText(_translate("TopoModifierDialogBase", "Select the topography raster for modification:"))
        self.selectTopoBaseButton.setText(_translate("TopoModifierDialogBase", "..."))
        self.label_2.setText(_translate("TopoModifierDialogBase", "Select vector layer containing masks:"))
        self.selectMasksButton.setText(_translate("TopoModifierDialogBase", "..."))
        self.useAllMasksBox.setText(_translate("TopoModifierDialogBase", "Use all masks in the layer."))
        self.label_3.setText(
            _translate("TopoModifierDialogBase", "Select the column and specify the name of the mask."))
        self.groupBox_3.setTitle(_translate("TopoModifierDialogBase", "Parameters for topography modification"))
        self.minMaxCheckBox.setText(_translate("TopoModifierDialogBase", "Use minimum and maximum values."))
        self.formulaCheckBox.setText(_translate("TopoModifierDialogBase", "Use formula for topography modification."))
        self.formulaGroupBox.setTitle(_translate("TopoModifierDialogBase", "Formula for topography modification"))
        self.label_4.setText(_translate("TopoModifierDialogBase",
                                        "Specify the column, which contains the formula or type it in the textbox:"))
        self.min_maxValueCheckBox.setText(
            _translate("TopoModifierDialogBase", "Constrain the values to be modified with minimum and maximum."))
        self.boundingValuesGroupBox.setTitle(_translate("TopoModifierDialogBase", "Bounding values"))
        self.minMaxValuesFromAttrCheckBox.setText(
            _translate("TopoModifierDialogBase", "Take the minimum and maximum values from the attribute table."))
        self.minMaxValuesFromSpinCheckBox.setText(
            _translate("TopoModifierDialogBase", "Enter the minimum and maximum values."))
        self.minValueLabel.setText(_translate("TopoModifierDialogBase", "Minimum:"))
        self.maxValueLabel.setText(_translate("TopoModifierDialogBase", "Maximum:"))
        self.minMaxGroupBox.setTitle(_translate("TopoModifierDialogBase", "Final minimum and maximum values"))
        self.minMaxFromAttrCheckBox.setText(
            _translate("TopoModifierDialogBase", "Take the minimum and maximum values from the attribute table."))
        self.label_5.setText(_translate("TopoModifierDialogBase", "Minimum value:"))
        self.label_6.setText(_translate("TopoModifierDialogBase", "Maximum value:"))
        self.groupBox_2.setTitle(_translate("TopoModifierDialogBase", "Output"))
        self.outputLaber.setText(_translate("TopoModifierDialogBase", "Output file path:"))
        self.helpBox.setPlaceholderText(
            _translate("TopoModifierDialogBase", "Here we shall see the help text for the tool. "))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("TopoModifierDialogBase", "Parameters"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("TopoModifierDialogBase", "Log"))
        self.cancelButton.setText(_translate("TopoModifierDialogBase", "Cancel"))
        self.runButton.setText(_translate("TopoModifierDialogBase", "Run"))
        self.closeButton.setText(_translate("TopoModifierDialogBase", "Close"))


from qgscollapsiblegroupbox import QgsCollapsibleGroupBox
from qgsfieldcombobox import QgsFieldComboBox
from qgsfilewidget import QgsFileWidget
from qgsmaplayercombobox import QgsMapLayerComboBox
